services:
  go-rest-api-db:
    image: postgres
    container_name: go-rest-api-db
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: default
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - go-rest-api-network

volumes:
  postgres:

networks:
  go-rest-api-network: